<?php

namespace AppBundle\Repository;

use AppBundle\Entity\QbException;

/**
 * QbExceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QbExceptionRepository extends \Doctrine\ORM\EntityRepository
{
    public function create($errorCode, $errorMessage, $purchaseItem) {
        $em = $this->getEntityManager();

        $qbException = new QbException();

        $qbException->setErrorCode($errorCode)
            ->setErrorMessage($errorMessage)            
            ->setPurchaseItem($purchaseItem);           

        $em->persist($qbException);
        $em->flush();

        return $qbException;
    }
    public function findByCompany($companyId){
        $qbExceptions = $this->getEntityManager()
                            ->createQueryBuilder()
                            ->select('e')
                            ->from('AppBundle:QbException', 'e')
                            ->innerJoin('e.purchaseItem','pi')
                            ->innerJoin('pi.purchase','p')                             
                            ->innerJoin('p.project','proj')                            
                            ->innerJoin('proj.company','c')
                            ->where("c.id = :company_id")
                            ->andWhere("e.isExported = :is_exported")
                            ->setParameter('company_id', $companyId)
                            ->setParameter('is_exported', false)                         
                            ->getQuery()
                            ->getResult();
        return $qbExceptions;                          
    }

}
