FOS\UserBundle\Model\User:
    exclusion_policy: ALL
    properties:
        email:
            expose: true
        id:
            expose: true
        # enabled:
        #     expose: true
        # locked:
        #     expose: true